### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#115]
I would suggest that we work towards a first release on maven central. We are going to be adding features but I now expect that the vast majority of the current API will remain stable and backwards compatible. Let's do some review and see if there is anything that needs to be done before the MC release. @cmungall

**Comment by cmungall** [comment]
Sounds good. First time submission to MC is a pain but not so bad after that

**Comment by pnrobinson** [comment]
duplicate with #142 closing
