### ISSUE TITLE
delete GoOntology class

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#124]
This class is a wrapper around Ontology but does not add any functionality and can be deleted without losing anything.

**Comment by pnrobinson** [comment]
On second thought, I will use this to add some special GO functionalities having to do with the subontologies and GO-specific relations.

**Comment by cmungall** [comment]
there shouldn't be go-specific relations as such. part-of etc will be found in many ontologies (regulates less so, but not unique to go)
