### ISSUE TITLE
Possible issue with GO Parser

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#126]
Phenol has a GO Parser integrated but as far as I can see the parser does not distinguish between different types of edge (is-a, part-of, etc). This is pretty important. I would like t get a set of genes associated with a phenotype and then use Ontologizer to find overrepresented GO terms.  
My goal is to have some bridge between phenol and Ontologizer algorithms, but unfortunately the interfaces are not that similar. @cmungall -- do you have a sense of what the most robust way forward would be. I do not think we can leave the GO Parser as is, and so either we refactor it or we remove it and have phenol just have phenotype ontologies.

**Comment by cmungall** [comment]
I would have a generic parser that distinguishes between the different relationship types, and populates edge types in the graph object based on these.

Then outside the parser/IO layer you can have a way of either dynamically filtering a graph based on relationship types or a utility to make a copy with a chosen set of relationship types.

(Note for GO this latter functionality may not be necessary as we make what we intend to be "bioinformatician-friendly" editions of the GO called go-basic (http://www.geneontology.org/page/download-ontology) that has the core relationships to propagate over; but it is very useful to have this functionality in general)

You might want to look at the subontology method of ontobio and implement an analogous procedure: https://ontobio.readthedocs.io/en/latest/api.html

Note also that we are considering for some pheno ontologies (such as MP and hopefully HP if you are willing) to switch some is-as to a causal relationship. cc @dosumis https://github.com/obophenotype/upheno/issues/291 - it would be great if phenol was "ready" for this out the box.

**Comment by pnrobinson** [comment]
The current GO parser is seemingly just ingesting is-a relations. I am adding the GO-specific relation types and will try to refactor the parser.

**Comment by pnrobinson** [comment]
This is the issue (Owl2OboTermFactory
```
// It seems that only actual relation used across ontologies is "IS_A" one for now.
  @Override
  public Relationship constructRelationship(TermId source, TermId dest, int id) {
    return new Relationship(source, dest, id, RelationshipType.IS_A);
  }
```
While HP and MP onlpy have IS_A, the GO has a number of other relations that are getting clobbered by this. TODO -- figure out where to get the relations and refactor this!

**Comment by pnrobinson** [comment]
@cmungall  -- is this correct?
Should the parser ignore triples with subPropertyOd and inverseOf ?

These are the relations we get with ``Edge edge `` and ``edge.getPred()``

is_a
http://purl.obolibrary.org/obo/RO_0002211 -regulates
http://purl.obolibrary.org/obo/RO_0002212 -negatively regulates
http://purl.obolibrary.org/obo/RO_0002213 -positively regulates
http://purl.obolibrary.org/obo/RO_0002092 -happens during
http://purl.obolibrary.org/obo/RO_0002093 -ends during
http://purl.obolibrary.org/obo/BFO_0000050 -part of
http://purl.obolibrary.org/obo/BFO_0000051 -has part
http://purl.obolibrary.org/obo/BFO_0000066 -occurs in
subPropertyOf
inverseOf

**Comment by pnrobinson** [comment]
Also, in terms of calculating ancestors for term enrichment, I would restrict to is_a and part of -- correct? @cmungall

**Comment by pnrobinson** [comment]
We have previously added this in order not to pull in OIO and IAO entities
```
 if (node.getType()==null || ! node.getType().equals(Node.RDFTYPES.CLASS)) {
        continue; // only take classes-- otherwise, we may get some OIO and IAO entities
      }
```
This does the trick for HP and MP, but with GO we do pull in three classes from RO and two from BFO, that I can see if we search for rel.getRelationshipType().equals(RelationshipType.SUBPROPERTY_OF) || rel.getRelationshipType().equals(RelationshipType.INVERSE_OF)

```
Relationship [source=TermId [prefix=TermPrefix [value=RO], id=0002092], dest=TermId [prefix=TermPrefix [value=RO], id=0002093], id=26134, relationshipType=SUBPROPERTY_OF]

Relationship [source=TermId [prefix=TermPrefix [value=BFO], id=0000050], dest=TermId [prefix=TermPrefix [value=BFO], id=0000051], id=71451, relationshipType=INVERSE_OF]

Relationship [source=TermId [prefix=TermPrefix [value=RO], id=0002212], dest=TermId [prefix=TermPrefix [value=RO], id=0002211], id=82946, relationshipType=SUBPROPERTY_OF]

Relationship [source=TermId [prefix=TermPrefix [value=RO], id=0002213], dest=TermId [prefix=TermPrefix [value=RO], id=0002211], id=83051, relationshipType=SUBPROPERTY_OF]
```
I will add some code to ``OboOntologyLoader`` that will remove all nodes with the class of BFO and RO -- these are not needed for the downstream work in phenol.

**Comment by pnrobinson** [comment]
This has been fixed & is now tested
