### ISSUE TITLE
Create a bridge to OWLAPI to enable use of OWL files in OLPG

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenol#13]
Currently OLPG only parses obo files. It would be useful to use OWL files since obo format is deprecated. However, OWL is difficult to work with, so we should have a bridge layer that maps OWL constructs onto a graph.

This would be a new class:

`com.github.phenomics.ontolib.io.base.OntologyOwlParser`

We can also make HpoOwlOntologyParser, MpoOwlOntologyParser (these will work in the same way, see #7 ).

The simplest way to do this is to use the java obographs library as a bridge - this would be one addition to the pom

```
<!-- https://mvnrepository.com/artifact/org.geneontology/obographs -->
<dependency>
    <groupId>org.geneontology</groupId>
    <artifactId>obographs</artifactId>
    <version>0.1.0</version>
</dependency>
```

We would then map from its internal model to the OLPG one. This also gives parsing of [obographs](https://github.com/geneontology/obographs/) for free

**Comment by yy20716** [comment]
Ok, let me put my questions here first.

**Q1**. The first problem is that [Obographs](https://github.com/geneontology/obographs) often handle some properties or axioms differently than others, e.g., 
 - It seems that obographs represent annotation properties such as `NCIT_P108` using class `BasicPropertyValue`. From my observation, such properties are not captured as graph's edges (it seems that only object properties are considered as edges?). 
 - Similarly, some owl files contain `PropertyChainAxioms` and these chaining statements do not exist in graph's edges. 
So my question is that what would be the best way to handle this problem? Should I include and map all these missing edges or just skip them?

**Q2**. When I checked the command line options of OLPG, there were only two specific operations named as `MergeScores` and `PrecomputeScores`, which may be designed for specific ontologies only (e.g., HPO?). I guess these operations could not be used for NCIT. Can you suggest any test operations that can be used over this loaded ontology or would it be enough if I could compare ontologies loaded from OBO and OWL? Please advise. Thank you.

**Comment by pnrobinson** [comment]
I believe that most of the ontologies for which OLPG are designed will have a relatively limited set of properties in their obo versions. It would be important to scope the goals of the OWL parser. For the HPO, at least, I think the main goal is to decorate the simple is-a graph with additional information that is not available in the obo translation; for instance to add some information about the affected uberon class when available. I think it would be useful to just sketch out on paper what the graph would look like and then decide how to implement the code.
OLPG is not currently extensively unit-tested, and especially the annotation part of the library is still primitive. I think we need to give thought to how to make the annotation section of the library easily testable; this is difficult because the annotation files for HP are very different from those of MP etc.
So maybe it would be good to skype about all of this?

**Comment by cmungall** [comment]
I was thinking one of the first goals would be to allow developers to easily use OLPG methods with ontologies that are either not available in OWL, or for which the .obo file cannot be parsed with the existing OLPG obo parser (e.g. NCIT).

The goals here would strictly be limited to ontology parsing, and not annotations

**Comment by yy20716** [comment]
* Uh ok, I will not concern about additional properties/annotations for now but I believe we could decide what to do with annotations after we would have calls later.
* I wonder what "OLPG methods"  mean, though. I saw a number of generic graph/similarity comparison algorithms implemented in OLPG. Did you mean, once we finished parsing basic structures of graphs in owl files, our next goal is to consider providing interfaces users to import owl and use such algorithms? Any suggestions/clarifications would be appreciated. Thank you.

**Comment by pnrobinson** [comment]
?Do we want to have a skype to discuss the overall roadmap for OLPG? Right now I most want to add in functionality for dealing with annotation models for HP, MP (mouse and rat) etc etc, but we need to decide on goals and scope

-Peter


Peter Robinson

Professor and Donald A. Roux Chair, Genomics and Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

New Book: Computational Exome and Genome Analysis<https://www.crcpress.com/Computational-Exome-and-Genome-Analysis/Robinson-Piro-Jager/p/book/9781498775984>

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by pnrobinson** [comment]
I think that this is now implemented with the new parser.
