### ISSUE TITLE
typo in HpoCategoryMap

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#146]
see https://github.com/TheJacksonLaboratory/hpo-web/issues/43

**Comment by pnrobinson** [comment]
fixed Repiratory => Respiratory with latest commit to develop (1.3.0-SNAPSHOT), will appear in version 1.3.0

**Comment by jmcmurry** [comment]
just saw this now; you can probably delete https://github.com/monarch-initiative/phenol/pull/150
