### ISSUE TITLE
MpAnnotation::merge chokes on sex-specific annotations with conflicting sex-specific normal fields 

### ISSUE THREAD

**Issue by hannahblau** [monarch-initiative/phenol#155]
@pnrobinson 
I fixed an error in the code for parsing sex-specific annotations, thereby revealing a different problem: MGI_Pheno_Sex.rpt has at least one (probably more) pair of annotations (from different PMIDs) that conflict in the sex-specific normal field (which determines whether or not the annotation is negated). Here's the first such example that caused the parsing to fail:

```
MGI:5888907	M	MP:0002912	abnormal excitatory postsynaptic potential	Rbfox3<tm1a(EUCOMM)Hmgu>/Rbfox3<tm1a(EUCOMM)Hmgu>	B6Dnk;B6N-Rbfox3<tm1a(EUCOMM)Hmgu>/H	N	27701470
MGI:5888907	M	MP:0002912	abnormal excitatory postsynaptic potential	Rbfox3<tm1a(EUCOMM)Hmgu>/Rbfox3<tm1a(EUCOMM)Hmgu>	B6Dnk;B6N-Rbfox3<tm1a(EUCOMM)Hmgu>/H	Y	26619789
```
the error looks like

```
org.monarchinitiative.phenol.base.PhenolException: Attempt to merge annotations only one of which is negated: MP:0002912
   at org.monarchinitiative.phenol.formats.mpo.MpAnnotation.merge(MpAnnotation.java:83)
   at org.monarchinitiative.phenol.io.obo.mpo.MpAnnotationParser.parsePhenoSexData(MpAnnotationParser.java:139)
   at org.monarchinitiative.phenol.io.obo.mpo.MpAnnotationParser.<init>(MpAnnotationParser.java:92)
   at org.monarchinitiative.phenol.io.obo.mpo.MpGeneParser.parseMpGeneModels(MpGeneParser.java:103)
   at org.monarchinitiative.dimorph.analysis.MpPhenoGeno.ingestMpData(MpPhenoGeno.java:86)
   at org.monarchinitiative.dimorph.analysis.MpPhenoGeno.<init>(MpPhenoGeno.java:66)
   at org.monarchinitiative.dimorph.command.AnalyzeDimorphic.execute(AnalyzeDimorphic.java:59)
   at org.monarchinitiative.dimorph.Dimorph.main(Dimorph.java:15)
```
I'm not sure what we want to do with cases such as this, but until we do something the parsing will fail. Perhaps preserve both annotations and avoid merging them? Or jettison the negated annotation and keep only the positive one?

**Comment by hannahblau** [comment]
I do not get the rationale for the following code that merges sex-specific annotations, lines 134-143 in MpAnnotationParser.java (whence comes the error message in previous comment). Couldn't one encounter two annotations for the same MP Id, one positive for (say) males and the other negative for females? Might be from different publications or the same publication. The code quoted below will throw a runtime error in this scenario (unless we revise the MpAnnotation.merge method).
```
      Map<TermId,MpAnnotation> annotset = geno2ssannotMap.get(genotypeId);
      if (annotset.containsKey(annot.getTermId())) {
        // there is a previous annotation for this MP term --
        // the current annotation is from a separate PMID
        MpAnnotation previousannot=annotset.get(annot.getTermId());
        MpAnnotation mergedannot=MpAnnotation.merge(previousannot,annot);
        annotset.put(mergedannot.getTermId(),mergedannot);
      } else {
        annotset.put(annot.getTermId(),annot);
      }
```

**Comment by pnrobinson** [comment]
meaning that if there is at least one abnormal annotation for a given MP term, then the merge records it as abnormal, even if there is also a sex-specific normal annotation for the term.

**Comment by pnrobinson** [comment]
Consider also refactor of the "negated" boolean as a modifer (male/female-specific normal).

**Comment by pnrobinson** [comment]
fixed & refactored!
