### ISSUE TITLE
OwlOntologyLoader and OboOntologyLoader - mostly duplicated internals

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/phenol#156]
The OntologyLoaders both use the [OWLAPI](https://github.com/owlcs/owlapi) to actually parse the input file and then the resulting OwlOntology is handed to the [obographs](https://github.com/geneontology/obographs) library for converting to a less intimidating data structure and this is then finally converted to a phenol graph.

For loading an OBO file this a overkill as the OWLAPI spends most of the CPU time converting an OBODoc instance into OWL and then this is converted back into a simpler form via obographs.

So my question is, apart from the term prefixes to ignore (RO, BFO in the case of the OboLoader and  OIO and IAO for the OwlLoader), why are these (currently) different at all?

As for the future - I'm going to cut out the OWLAPI and obographs steps in the OboOntologyLoader as these are a huge waste of resources.

**Comment by pnrobinson** [comment]
The decision to use OWLAPI was made for two reasons (1) the previous antlr parser was very difficult to maintain and extend (2) it is good to be able to parse OWL or OBO with minimal changes. 
That said, one of the major use cases of phenol will be to ingest hp.obo for algorithms, and thus it would definitely be worth exploring a fast and slank OBO parser, possibly even one that is specialized for HPO to begin with.

**Comment by julesjacobsen** [comment]
The OWLAPI uses the OBOFormatParser under the hood, which we can utilise directly, so we're not losing anything there. We've split OWL and OBO parsing into two distinct classes, although this is a mostly artificial distinction given they do things almost identically. I was mostly wondering about why these are different at all.

**Comment by cmungall** [comment]
My preference is to avoid propagating obo format parsers, obo format is 
a legacy format. Seems to make sense to have a single transform from 
obographs.

If speed of OWLAPI parsing is a concern: Note it's trivial to add a 
.json to the hpo release process. The json will soon be ubiquitous for 
all OBOs. Then you avoid the overhead of the OWLAPI, it's json 
everywhere.

**Comment by julesjacobsen** [comment]
@cmungall I'm with you on the not propagating parsers thing, which is why I haven't and aren't suggesting doing so. I'm suggesting we cut out the intermediate transformations from:

```File -> OBODoc -> OWLOntology -> GraphDocument -> (Terms and Relations) -> Ontology``` 

and just transform it ourselves like this:

```File -> OBODoc -> (Terms and Relations) -> Ontology```
(_note_ the  OBODoc -> OWLOntology transform is internal to the OWLAPI and takes longer than it does to parse the file in the first step)

Currently the ```GraphDocument -> (Terms and Relations) -> Ontology``` steps are all intermingled. They can be relatively easily separated which means we should be able to switch parser implementations more easily. Where is the new json OBO format defined? Are there parsers/writers for this anywhere?

**Comment by cmungall** [comment]
Ah, I see. I always forget about that OBODoc intermediate object. This is a pretty crappy datamodel just designed to support the initial parse step. But at least this avoids another parser.

I'd still try and nudge you towards the path of having phenol rely solely on GraphDocument and only having one transform (with reliance on json when speed is a concern). But whatever you think best.

**Comment by julesjacobsen** [comment]
Ah, I also realise I was being a bit dim - obographs does the json/yaml serialisation so, yes it would make sense to use that. Although this assumes ontologies will become generally available in json.

Is there going to be a move to actually deprecate OBO format and replace that with json? Will Protege/Oboedit have a load/save json option relying on obographs as layer to do this?

**Comment by pnrobinson** [comment]
@drseb @cmungall @julesjacobsen  Why don't we start releasing the HPO as JSON then? Is there anything stopping us?

**Comment by pnrobinson** [comment]
@julesjacobsen Do we have an action item/decision for this issue?

**Comment by julesjacobsen** [comment]
Looks like it should be easy enough to ingest OBO, OWL or JSON using obographs as the final step before transforming the ```obographs.Graph``` to an ```Ontology```. Then we can do as Chris suggests and ingest JSON where available, or if we want a slow and painful existence OBO or OWL. I'm happy to make these changes.

Before I begin, what was the original rationale for having an OboOntologyLoader and an OwlOntologyLoader where they appear to be mostly copy/pasted internally? There may be some subtle distinctions I missed when I refactored the OboOntologyLoader.

**Comment by pnrobinson** [comment]
AFAIK there was no subtle distinctions, rather, this was simply a part of trying out solutions as a part of the refactoring process from the original ANTLR parser. So, go for it!

**Comment by cmungall** [comment]
> My understanding is that there should be no difference in this transform step whether the ontology started out life as an OWL or OBO ontology. Can you confirm this?

correct

**Comment by julesjacobsen** [comment]
Fixed in  commit c262711 and 62db7d0c028165f6e832c85105f855300f16bade and a few more besides

**Comment by julesjacobsen** [comment]
Ah no - spoke too soon. I've refactored the Obo/OwlOntologyLoader internals to be the same.

**Comment by julesjacobsen** [comment]
@cmungall does robot output use obographs to do this conversion? Is the output a ```Graph``` or a ```GraphDocument```? Seems like the obographs.io classes all read and write a ```Graph```, but the ```FromOwl``` class returns a ```GraphDocument```. Which should I be expecting from the robot json output?

**Comment by julesjacobsen** [comment]
@pnrobinson I'm trying to push my final changes, but you're making conflicts! Hold fire for a few minutes!

**Comment by julesjacobsen** [comment]
see e7531dadf4e732f4f90969b27cf8be603e1ed936 and 7e09baa
