### ISSUE TITLE
TermId construction error should not be a RuntimeException

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#157]
org.monarchinitiative.phenol.base.PhenolRuntimeException: TermId construction error: "" does not have a prefix!

Let's alter this so that we can record what actually went wrong...this would be more useful that just failing.

**Comment by julesjacobsen** [comment]
But, that is what went wrong! You passed in an empty string, which isn't a valid TermId.

**Comment by pnrobinson** [comment]
Yes, but it would be good to have some more context about where the "" is coming from and this is not possible if the TermId throws a RuntimeException like this -- we would want to know the line of the OBO file where this is coming from, for instance.

**Comment by julesjacobsen** [comment]
You can wrap the relevant part of the parser with a try/ catch and convert that to a helpful message - 

```java

try {
    TermId.of(token);
} catch (PhenolRuntimeException ex) {
    logger.error("Error at line {} {}", line, ex);
}

**Comment by pnrobinson** [comment]
I thought that RunTimeExceptions were intended to be used for things like array out of bounds where you cannot really recover. Perhaps it would be cleaner if we use another checked exception custom subclass and caught it as above.

**Comment by julesjacobsen** [comment]
Having this a TermId.of() throw a checked exception will make 90% of code unbearable to use. Also - what are you going to recover from here? You can't really correct your input file on the fly.

    Integer.parseInt(String value)

Throws an unchecked exception which can be caught and handled if required. I think this is a reasonable trade-off. The other alternative is to simple accept whatever comes in and make something up if it's unacceptable, but I think that's a bad idea.

**Comment by pnrobinson** [comment]
OK, I see what you mean. Then I will implement your first suggestion!

**Comment by pnrobinson** [comment]
Closing this issue, will implement above suggestions as needed!
