### ISSUE TITLE
refactor PValue class

### ISSUE THREAD

**Issue by kingmanzhang** [monarch-initiative/phenol#160]
https://github.com/monarch-initiative/phenol/blob/e71323d915f89ac1f73f8867edbbb5a31569a2d5/phenol-analysis/src/main/java/org/monarchinitiative/phenol/stats/PValue.java

add a constructor and make fields private

**Comment by pnrobinson** [comment]
1+

**Comment by pnrobinson** [comment]
I refactored this class. We will need to refactor quite a bit of these classes. but I think we should make separate issues to reimplement parts of Ontologizer here.
