### ISSUE TITLE
TermPrefix

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#165]
@julesjacobsen 
There is no reason to keep the TermPrefix class any longer? I would like to delete the class before we go onto maven central since it has no point now and will only cause confusion or am I missing something?

**Comment by julesjacobsen** [comment]
You're right, it ought to go. It was used in the tests but I'll clean that up.

**Comment by julesjacobsen** [comment]
done: 4309a18a5f6853351bcc24b3814e34fdf6b59ef1
