### ISSUE TITLE
Make ImmutableOntology private

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#179]
Client code should use the Builder
```
public ImmutableOntology(
      ImmutableSortedMap<String, String> metaInfo,
      DefaultDirectedGraph<TermId, IdLabeledEdge> graph,
      TermId rootTermId,
      Collection<TermId> nonObsoleteTermIds,
      Collection<TermId> obsoleteTermIds,
      ImmutableMap<TermId, Term> termMap,
      ImmutableMap<Integer, Relationship> relationMap) 
```

**Comment by julesjacobsen** [comment]
@pnrobinson This mainly affects the test classes - I've made the change, but there is a issue with the ```OntologyAlgorithmRelationshipTest``` I think it was a mistake in the original test code where the relationships were created backwards.

I'll commit what I have now and clean-up tomorrow.
