### ISSUE TITLE
release

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#180]
@ielis Can we make the 1.3.2 release? I think we have addressed all of the issues -- the ECTO parser should now also be ok actually.

**Comment by ielis** [comment]
Yes, I can make the release from my phenol fork. It would be easier if I had push privilege, though.

**Comment by pnrobinson** [comment]
done! thanks

**Comment by ielis** [comment]
Hi Peter, the release 1.3.2 has been published. It will take a few hours to appear in the Maven Central.
