### ISSUE TITLE
CURIE key conflict

### ISSUE THREAD

**Issue by kingmanzhang** [monarch-initiative/phenol#182]
If a CURIE has been defined in curie_map.yaml and user provided again in CurieUtil, it will crash because of key conflict. Maybe allow overwrite?

**Comment by pnrobinson** [comment]
@kingmanzhang can we discuss this? Let's try to find a fix. Can we make a unit test for this?

**Comment by julesjacobsen** [comment]
This is extremely easy to test and fix. We just need to decide whether or not to allow this behaviour. It's safest to crash when keys are duplicated in the curie_map.yml  as this indicates a potential error and prevents erroneous values. For the case of a user wishing to override, it makes sense not to crash, but we ought to make it possible for a user to check for the the existence of a key first (might already be possible). Or maybe this isn't important?

**Comment by pnrobinson** [comment]
@kingmanzhang @julesjacobsen Is this something we can fix before the 1.3.4 release (hopefully next week)?

It seems that ``CurieUtilBuilder`` is reading ffrom the phenol-io src/resources/curie_map/yml

Would we need to alter the function ``withDefaultsAnd``? I am not familiar with the CurieUtil library.

**Comment by julesjacobsen** [comment]
It's a question of allowable behaviour. Do we want to allow default values to be overridden? If yes I suggest we check the input and alert the user in the log as an INFO or maybe WARN and leave it at that. 

Alternatively we keep the existing behaviour, which is safe as it contains no surprises after the initial complete system failure. It's entirely possible for the user to check existing entries in default map as this is exposed as `CurieUtilBuilder.DEFAULT_CURIE_MAP` and they can create their own merged map and supply that to `CurieUtilBuilder.just(merged)`

Or a third alternative is to add another method called something like `CurieUtil.withOverwriteDefaultsAnd()` which will do the merging and alert the user in the logs. But then we have to assume the user has read the docs and understands the difference between the methods, which they won't.

**Comment by pnrobinson** [comment]
@kingmanzhang  what was the use case for allowing overwrite? Can we leave things as is or should we change the behavior?

**Comment by kingmanzhang** [comment]
I made the original request because I wanted to provide missing CURIEs by providing all CURIEs I need. This resulted in conflicts. Now the yaml map has all what I need, so I think we can keep things as they are and deal with it if when we have to in future.

**Comment by pnrobinson** [comment]
OK super -- let's keep things as is and add to the curie map as needed
