### ISSUE TITLE
1.3.3 release

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#192]
Can we plan a maven central release after we have dealt with the currently open issues? Is there anything else that is pressing? @ielis @julesjacobsen @cmungall

**Comment by pnrobinson** [comment]
@julesjacobsen @ielis I am thinking it might be good to publish release 1.3.3 now and not wait until we have finished all of these items, since a lot of client code is now dependent on local maven installs. Can we release?

**Comment by pnrobinson** [comment]
We are in the process of releasing 1.3.3 on maven central -- thanks Daniel! We still need to merge the new master into develop and reset the version to 1.3.4-SNAPSHOT

We should probably start to think of a version 1.4 that we could publicize on the HPO mailing list and webpage.

**Comment by julesjacobsen** [comment]
@pnrobinson Sorry, I've been completely side-tracked on other things. Yes, by all means release. The couple of issues I have open could both go into 1.4.0.

**Comment by pnrobinson** [comment]
@julesjacobsen no worries, in same boot, let's see if we can make the above changes for 1.4.0 a little later.
We have release 1.3.3
