### ISSUE TITLE
phenotypicAbnormalities of HPODisease include HPO termIds that are not phenotypic abnormalities

### ISSUE THREAD

**Issue by hannahblau** [monarch-initiative/phenol#199]
Some categories of HPO term get added to the list of phenotypic abnormalities for an **HPODisease** even though these  terms are not descendants of HP:0000118, _Phenotypic abnormality_. Two examples:

HP:0003828, _Variable expressivity_
HP:0003829, _Incomplete penetrance_

both are children of HP:0003812, _Phenotypic variability_ which is a HP:0012823, _Clinical modifier_. Here are two lines where HP:0003828 and HP:0003829 occur in phenotype.hpoa (downloaded 14 January 2019):
```
OMIM:155255	MEDULLOBLASTOMA		HP:0003829	OMIM:155255	TAS					M	HPO:skoehler[2017-07-13]
OMIM:616924	CHARCOT-MARIE-TOOTH DISEASE, AXONAL, TYPE 2CC		HP:0003828	OMIM:616924	TAS				HPO:skoehler[2017-07-13]
```
I think the issue lies in the following lines from the parse() method of **HpoDiseaseAnnotationParser**:
```
      try {
          if (this.isInheritanceTerm(line.getPhenotypeId())) {
              inheritanceListBuilder.add(line.getPhenotypeId());
          } else if (line.isNOT()) {
              negativeTermListBuilder.add(line.getPhenotypeId());
          } else {
              HpoAnnotation tidm = HpoAnnotationLine.toHpoAnnotation(line, this.ontology);
              phenoListBuilder.add(tidm);
          }

          if (line.getDbObjectName() != null) {
              diseaseName = line.getDbObjectName();
          }
      } catch (Exception var22) {
          errorbuilder.add(String.format("PHENOL ERROR] Line: %s--could not parse annotation: %s ", line.toString(), var22.getMessage()));
      }
```
Checks for inheritance terms but not clinical modifiers (or possibly other categories that might wind up in phenotype.hpoa?).

**Comment by pnrobinson** [comment]
Good suggestions

**Comment by kingmanzhang** [comment]
A clinical course term HP:0003678 Rapidly progressive is also seen in phenotypic abnormalities, which crashed Phenomiser (possible LR2PG as well).

**Comment by pnrobinson** [comment]
fixed, thanks @kingmanzhang and @hannahblau
