### ISSUE TITLE
release 1.3.4

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#212]
Let address the following issues and release
- [x]  https://github.com/monarch-initiative/phenol/issues/210
- [x]  https://github.com/monarch-initiative/phenol/issues/208
- [x]  #204 
- [x]  #209
- [x]  #196 
- [x]  #183 
- [x]  #195
- [x]  #213
- [x] #203

**Comment by pnrobinson** [comment]
@julesjacobsen @iimpulse @ielis @cmungall since nobody has been shouting I will release the 1.3.4 next week on Monday or Tuesday. I will also accept the PR for the new features as I think a few people have looked at it and all the tests are OK. I am going to plan on cleaning up some error warnings and doing a little more testing of the extended Orphanet Parser on Monday before finalizing.

**Comment by julesjacobsen** [comment]
Fine by me. I'd only ask you think about the version numbering - if you've done anything to break the existing API, this should be a version 2.0.0 release.

**Comment by pnrobinson** [comment]
the API will be changed slightly (the Hpo annotation CTOR) but not in a way that will change the behavior of the program. At present, we have not publicized phenol at all and so afaik there are no external users. Let's go with 1.4.0, so as not to be inflationary with version numbers. At some point this year we should write an application note and then be strict about this.

**Comment by pnrobinson** [comment]
I think we are ready to release, but I am getting an error from travis:

https://travis-ci.org/monarch-initiative/phenol/builds/550014903?utm_medium=notification&utm_source=email

Look into this tomorrow

**Comment by pnrobinson** [comment]
Release 1.4.0 is available now on maven central @ielis @iimpulse @julesjacobsen
