### ISSUE TITLE
PhenotypeDotHpoaFileWriter

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#217]
This file uses maps that are created by Phenol. It would be more convenient to refactor this such that client code (HpoAnnotQc) can be run something like this

```
String small_file_dir = ...;
String orphaPhenotypeXml = "en_product4.xml";
String orphaInheritanceXml = "en_product9_ages.xml"
PhenotypeDotHpoaFileWriter writer = new PhenotypeDotHpoaFileWriter(small_file_dir,orphaPhenotypeXml,orphaInheritanceXml);
// The CTOR parses and merges the data
writer.write(); // optionally set path by default "phenotype.hpoa in PWD
```
Only RunTimeExceptions are allowed.

**Comment by julesjacobsen** [comment]
Related question - do you use the `en_product6.xml`? This contains the Disease/Susceptibility modifiers for a condition. I wonder if it would simply be easier to import the ordo.owl and work with that directly as it contains all the data in one place?

**Comment by pnrobinson** [comment]
@julesjacobsen we are currently not using en_product6.xml -- because the diseases that we are getting from the Orphanet HPO dataset are all Mendelian and so no further check is necessary. Could you possibly create a new issue with the use case/need for this file? It would be not too onerous to parse it too.

**Comment by pnrobinson** [comment]
The phenotype.hpoa is parsing successfully, so I will close this.

**Comment by julesjacobsen** [comment]
We import all of the Orphanet models for the Exomiser but non-mendelian diseases shouldn't have a mode of inheritance so I guess that should be OK then.
