### ISSUE TITLE
travis error

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#244]
I think that maybe we need to move to openJDK for license issues? 
We could also move to Java 11?
```
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

**Comment by julesjacobsen** [comment]
What branch are you using? develop is already built against openJDK 8 and 11 see 223fcfc
