### ISSUE TITLE
countObsoleteTerms

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#251]
This method is returning the number of obsolete TermIds (i.e., alt_ids), not the number of obsolete terms. The method is working but we need to rename the function to ``countObsoleteTermIds``.
I will do this if there are no objections this week.

**Comment by pnrobinson** [comment]
I think the best labels are 'countAltIds' and 'countPrimaryIds'

**Comment by julesjacobsen** [comment]
Agreed, these are much less ambiguous labels!

**Comment by pnrobinson** [comment]
fixed
