### ISSUE TITLE
Investigate differences between old pipeline and phenol when generating artefacts

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/phenol#253]
placeholder ticket, after conversation in today's leads talk

to investigate where differences are stemming from and find solutions

**Comment by pnrobinson** [comment]
This is one area that there seem to be differences in:
https://github.com/monarch-initiative/phenol/issues/258

**Comment by pnrobinson** [comment]
I have been comparing the pheol-derived disease genes with the file ``gene_to_phenotype.txt``
There appear to be genes that are missing from gene_to_phenotype. I think the latest version (not yet online!) appears to have fixed the issue you pointed out with the tRNA genes (thanks!)

 I am not sure if I am doing everything correctly, but with HPOworkbench I wrote a command to compare this file to the files produced by phenol. There are a few hundred genes in the genes in the phenol map that are not in ``gene_to_phenotype.txt``. Here are some examples:

```
NCBIGene:4848 in Ch map. CNOT2 Intellectual developmental disorder with nasal speech, dysmorphic facies, and variable skeletal anomalies 	618608  
NCBIGene:113263 in Ch map. GLCCI1 {Glucocorticoid therapy, response to} 	614400 => This gene is visible on the HPO website, but with no associations -- it is suceptiblity and probably needs to be added to omit list
NCBIGene:2215 in Ch map. FCGR3B  ORPHA:464370 Neonatal alloimmune neutropenia
```

There are two genes in ``gene_to_phenotype.txt`` that are not in phenol

NCBIGene:57135, DAZ4: https://omim.org/entry/400048
and  NCBIGene:4291 MLF1: https://omim.org/entry/601402

these genes do not have a phenotypic association in OMIM, but do in Orphanet, and so somehow are pipeline is missing them.

**Comment by pnrobinson** [comment]
@drseb Did you have a chance to look at the examples above that are not in gene_to_phenotype.txt?

**Comment by drseb** [comment]
CNOT2 is missing because there are no HPO annotations for 618608

**Comment by drseb** [comment]
same for 614400

**Comment by drseb** [comment]
same for Orpha:464370

so I conclude: no errors in my pipeline - all expected behaviour

**Comment by pnrobinson** [comment]
@drseb 
Here is another difference -- DAZ4. I do not think that either Orphanet or OMIM are saying that this gene is associated with a disease. Here is the stanza from en_product6: Candidate gene tested in
```
 <DisorderGeneAssociation>
          <SourceOfValidation>20671934[PMID]_14639527[PMID]</SourceOfValidation>
          <Gene id="15849">
            <OrphaNumber>121020</OrphaNumber>
            <Name lang="en">deleted in azoospermia 4</Name>
            <Symbol>DAZ4</Symbol>
            <SynonymList count="0">
            </SynonymList>
            <ExternalReferenceList count="5">
              <ExternalReference id="57068">
                <Source>Ensembl</Source>
                <Reference>ENSG00000205916</Reference>
              </ExternalReference>
              <ExternalReference id="37421">
                <Source>Genatlas</Source>
                <Reference>DAZ4</Reference>
              </ExternalReference>
              <ExternalReference id="28481">
                <Source>HGNC</Source>
                <Reference>15966</Reference>
              </ExternalReference>
              <ExternalReference id="46811">
                <Source>OMIM</Source>
                <Reference>400003</Reference>
              </ExternalReference>
              <ExternalReference id="32860">
                <Source>SwissProt</Source>
                <Reference>Q86SG3</Reference>
              </ExternalReference>
            </ExternalReferenceList>
            <LocusList count="1">
              <Locus id="14065">
              </Locus>
            </LocusList>
          </Gene>
          <DisorderGeneAssociationType id="18273">
            <Name lang="en">Candidate gene tested in</Name>
          </DisorderGeneAssociationType>
          <DisorderGeneAssociationStatus id="17997">
            <Name lang="en">Not yet assessed</Name>
          </DisorderGeneAssociationStatus>
        </DisorderGeneAssociation>
```

**Comment by pnrobinson** [comment]
CNOT2 needs to be added, I will add it to the list.

**Comment by drseb** [comment]
Thanks. Will look into it asap.

**Comment by pnrobinson** [comment]
I am closing this now -- I think that the differences now reflect logic differences between the approaches.
