### ISSUE TITLE
Javadoc and java 11

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#265]
It is possible to compile phenol with java 11 but one needs to disable Javadoc
```
mvn install -Dmaven.javadoc.skip=true
```
This is related to : https://stackoverflow.com/questions/58836862/jdk-11-and-javadoc
However, even the solution proposed there does not work
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-javadoc-plugin</artifactId>
  <configuration>
    <source>8</source>
  </configuration>
</plugin>
```
Is there any other way?
I am guessing we will need to modularize phenol to get this to work again. Java 14 was released recently and this would be good.

**Comment by ielis** [comment]
The build now works with
```bash
cd phenol
./mvnw clean install
```
