### ISSUE TITLE
Header lines should start with #

### ISSUE THREAD

**Issue by drseb** [monarch-initiative/phenol#287]
Please consider starting all header lines in the file phenotype.hpoa to start with #, i.e. the line that defines the header should also start with this character. 

Thanks for considering.

**Comment by pnrobinson** [comment]
This is a good idea. We will implement this in the next release (prob next week), and then we just need to adjust the make file of HpoAnnotQc and re-run Hudson...

**Comment by pnrobinson** [comment]
I have added this to phenol and it will be available in the 1.6.0 version to be released in the new several days. We will need to revise the Makefile in travis. (TODO)
