### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#29]
I think our consensus was phenotype ontology library -- phenol
If nobody shouts, I will make the name change tomorrow!

**Comment by kingmanzhang** [comment]
You could name releases with colors' names(e.g. from short to long wavelengths). That makes a cool combo!

**Comment by pnrobinson** [comment]
@yy20716 @cmungall @mellybelly @drseb 
I think that we now have consensus about the name. I would suggest we merge all of the branches, and then change the name (including of the package path). 
org.monarchinitiative.phenol
If nobody shouts, I will do so this afternoon or tomorrow morning. Or if anybody else would like to do the honors, go ahead, but please enter a comment here.

**Comment by yy20716** [comment]
Ok, I made a pull request for this issue, but I guess someone may needs to update repository name manually if needed. Thank you.

**Comment by pnrobinson** [comment]
I have updated the package names in IntelliJ. I also updated the version to 0.1.5 (I will hotfix the Changelog). Please test that everything is working at your end!

**Comment by yy20716** [comment]
ok, I confirmed running maven did not have issues and all tests were passed. I found that group ids in pom.xml files were not updated, so I made a pull request about this issue [here](https://github.com/monarch-initiative/phenol/pull/34). If this is not required, then please just discard it. Thank you.

**Comment by pnrobinson** [comment]
THere are a few other paths that need to be changed to use phenol in applications, I am currently trying out how to get this to work,

**Comment by pnrobinson** [comment]
things are working!
