### ISSUE TITLE
Refactor HpoDisease

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#3]
This class currently has a static internal class called TermIdWithFrequency. However, we need to have more metadata for the HpoDisease annotations including Onset. Also, it does not make sense to have a termidWithFrequeny for the inheritance term, as I would not use this in algorithms the same we we use phenotype frequencies, and we have zero data on this in our annotations. I will replace HpoDisease with a new class called HpoDiseaseWithMetadata, and add a new class called TermIdWithMetadata. We may want to refactor later on, but the code has been tested in an application and does what is needed.

**Comment by cmungall** [comment]
Why is it necessary to have this extra inner class at all?

Maybe this is too dumb but how about doing the simplest thing possible. A class `DiseaseToPhenotypeAssociation`, with:

 * TermID: Disease (do we need a MondoTermId?)
 * LogicalOperator: qualifier (e.g. NOT)
 * TermID: Phenotype
 * TermID: Onset
 * Frequency: frequency
 * Severity: severity
 * Provenance: provenance
 * Evidence: evidence

See also:

https://biolink.github.io/biolink-model/docs/DiseaseToPhenotypicFeatureAssociation.html

**Comment by pnrobinson** [comment]
This is now working, but I will leave this open until we have finished the refactor of the annotation format, when I will come back to this class one more time.

**Comment by pnrobinson** [comment]
@cmungall @yy20716 I have made a number of refactorings. I will explain this in person on Thursday, and we can plan improvements as needed from there. I am going to close this now and we can make new issues as needed.
