### ISSUE TITLE
Function to export FHIR Code System

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/phenol#310]

**Comment by iimpulse** [comment]
feature/fhir-code-system is where the work is being done.

**Comment by ametke** [comment]
@iimpulse @pnrobinson have you seen [this project](https://github.com/aehrc/fhir-owl)? This is what I use to generate the current HPO code system. You can see how it looks like [here](https://r4.ontoserver.csiro.au/fhir/CodeSystem/b4b35498-fe2c-4bda-8bfd-be7ec2a9f47b). A paper that explains the approach is available [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7153051/).

**Comment by pnrobinson** [comment]
@ametke thanks, this looks really nice, I was not aware of the paper. @iimpulse let's try this out!

**Comment by pnrobinson** [comment]
@iimpulse  @julesjacobsen 
added this
```
protected CodeSystem ontologyToCodeSystem(Ontology ontology) {
    // TODO: Traverse HPO and Build Logical Code System.
    TermId all = TermId.of("HP:0000001"); // root of everything
    Set<TermId> termIds = ontology.getNonObsoleteTermIds();
    for (TermId tid : termIds) {
      Term term =  ontology.getTermMap().get(tid);
      CodeType hpoCodeType = new CodeType(tid.getValue());
      CodeSystem.ConceptDefinitionComponent component = new CodeSystem.ConceptDefinitionComponent(hpoCodeType);
      component.setDefinition(term.getDefinition());
      component.setId(tid.getValue());
      component.setCode(term.getName());
      Set<TermId> children = OntologyAlgorithm.getChildTerms(this.ontology, tid, false);
      for (TermId childId : children) {
        component.addChild(childId.getValue());
      }
      List<CodeSystem.ConceptDefinitionComponent> compoentList = new ArrayList<>();
      compoentList.add(component);
      codeSystem.setConcept(compoentList);
    }
    return codeSystem;
  }

```
Do we have some way of testing this yet or should I set up some test classes? I doubt this is actuaqlly correct, but there is not so much documentation out there.
I am wondering if it would be good to place the FHIR code in a separate module so as not to add more dependencies to the io module. Also, @iimpulse I think @matzenglou will help us to add this to the HPO build and so the built code systems would appear in the GUtHub releases. Does that sound about right?

**Comment by ametke** [comment]
Hi all,

I would suggest using the parent property to represent the hierachy rather than nesting the concepts because this won't work well with multple parents. The standard properties in FHIR are available [here](https://www.hl7.org/fhir/codesystem-concept-properties.html). Here is an example of how this would look like:
```
{
  "code": "HP:0031122",
  "display": "Two-raphe bicuspid aortic valve",
   "property": [
     {
       "code": "parent",
       "valueCode": "HP:0001647"
    }
  ]
}
```
To implement this you need to iterate through all the parents of a concept and do the following (cdc is the current ConceptDefintionComponent):
```
final ConceptPropertyComponent parentProp = cdc.addProperty();
parentProp.setCode("parent");
parentProp.setValue(new CodeType(parentCode));
```

**Comment by pnrobinson** [comment]
@ametke  Thanks! Thanks so much for the advice. This is the result for a small test subset of HPO
```
<CodeSystem xmlns="http://hl7.org/fhir">
   <id value="hpo"></id>
   <url value="http://purl.obolibrary.org/obo/hp.fhir"></url>
   <version value="release/019293m3"></version>
   <name value="HPO"></name>
   <title value="Human Phenotype Ontology Coding"></title>
   <status value="active"></status>
   <experimental value="false"></experimental>
   <date value="2021-04-13T06:12:47-04:00"></date>
   <publisher value="The Human Phenotype Ontology"></publisher>
   <contact>
      <name value="Peter N. Robinson"></name>
   </contact>
   <description value="A FHIR code system representation of the Human Phenotype Ontology."></description>
   <purpose value="To provide a standardized vocabulary of human phenotypes encountered in human disease in a FHIR context."></purpose>
   <concept id="HP:0100886">
      <code value="Abnormality of globe location"></code>
      <definition value="An abnormality in the placement of the ocular globe (eyeball)."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0012374"></valueCode>
      </property>
   </concept>
   <concept id="HP:0012374">
      <code value="Abnormal globe morphology"></code>
      <definition value="An anomaly of the eyeball."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0012372"></valueCode>
      </property>
   </concept>
   <concept id="HP:0100887">
      <code value="Abnormality of globe size"></code>
      <definition value="An abnormality in the size of the ocular globe (eyeball)."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0012374"></valueCode>
      </property>
   </concept>
   <concept id="HP:0000528">
      <code value="Anophthalmia"></code>
      <definition value="Absence of the globe or eyeball."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0100887"></valueCode>
      </property>
   </concept>
   <concept id="HP:0012372">
      <code value="Abnormal eye morphology"></code>
      <definition value="A structural anomaly of the eye."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0000478"></valueCode>
      </property>
   </concept>
   <concept id="HP:0012373">
      <code value="Abnormal eye physiology"></code>
      <definition value="A functional anomaly of the eye."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0000478"></valueCode>
      </property>
   </concept>
   <concept id="HP:0000118">
      <code value="Phenotypic abnormality"></code>
      <definition value="A phenotypic abnormality."></definition>
   </concept>
   <concept id="HP:0000568">
      <code value="Microphthalmia"></code>
      <definition value="A developmental anomaly characterized by abnormal smallness of one or both eyes."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0100887"></valueCode>
      </property>
   </concept>
   <concept id="HP:0007686">
      <code value="Abnormal pupillary function"></code>
      <definition value="A functional abnormality of the pupil."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0012373"></valueCode>
      </property>
   </concept>
   <concept id="HP:0000478">
      <code value="Abnormality of the eye"></code>
      <definition value="Any abnormality of the eye, including location, spacing, and intraocular abnormalities."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0000118"></valueCode>
      </property>
   </concept>
   <concept id="HP:0000632">
      <code value="Lacrimation abnormality"></code>
      <definition value="Abnormality of tear production."></definition>
      <property>
         <code value="parent"></code>
         <valueCode value="HP:0012373"></valueCode>
      </property>
   </concept>
</CodeSystem>
```

**Comment by pnrobinson** [comment]
@iimpulse @matentzn  @drseb can we touch bases about the best way of adding this to the HPO build system?

**Comment by matentzn** [comment]
Can you send me the command to be run? I can figure it out probably!

**Comment by drseb** [comment]
Can we test this first? Are all values exactly the same as in the owl version?

**Comment by pnrobinson** [comment]
@drseb This is running from a small "mini-HPO" file, and I think the values are correct. I am going to build out the tests a bit now to check that the parents are correct, but on inspection this is the case.
I think it is probably best to make a separate FHIR module in phenol that will include a small app that creates this file -- @matentzn would that be a good for the build?

**Comment by matentzn** [comment]
From my perspective anything goes - you tell me the jar location and the command and I will add the output to the release pipeline! So yes, sounds good!

**Comment by drseb** [comment]
We can give it a test run in the release-test-env, but I am hesitant to move it directly into production. We need to check things like data version, licensing, etc. 
What is happening with synonym types?

**Comment by ametke** [comment]
Happy to help @pnrobinson! 

There is only one issue with the snippet above that should be easy to fix. The concept id should go in `code` and the concept description in `display`. So, for example, instead of 
```
<concept id="HP:0100886">
        <code value="Abnormality of globe location"></code>
```
this should be
```
<concept>
       <code value="HP:0100886"></code>
       <display value="Abnormality of globe location"></display>
```

Synonyms can be added using the _designation_ attribute in each concept. The result should look something like this (sorry, in JSON because it's my preferred format):
```
{
  "code": "HP:0000958",
  "display": "Dry skin",
  "designation": [
    {
      "use": {
        "system": "http://snomed.info/sct",
        "code": "900000000000013009",
        "display": "Synonym (core metadata concept)"
      },
      "value": "Xerosis"
    }
  ]
  ...
```

Regarding the version of the code system, is `release/019293m3` because this is a test? I was using the dates you use as tags in Github as the version and I think this would probably be better.

**Comment by drseb** [comment]
What about exact and related synonyms? Can they be distinguished in FHIR? 

Can you link the FHIR version of HP of the latest release please?

**Comment by ametke** [comment]
The value set bound to the `use` field is extensible so you can use a code that is not in the value set if none of the codes are applicable. If you want to distinguish exact from related synonyms you need a code for the latter (the current value set only defines _fully specified name_ and _synonym_). There is nothing in SNOMED CT to represent a _related synonym_ as far as I am aware, but this could come from another terminology.

**Comment by pnrobinson** [comment]
Thanks, @ametke  @julesjacobsen @iimpulse for help/advice! I have created an app to export the FHIR codesystem here https://github.com/monarch-initiative/pyrophen
This app uses the code from this branch and fixes/extends some issues.
Closing this issue and deleting the branch.
