### ISSUE TITLE
Java 14 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#317]
Phenol does not build under Java 14 or 15 (reproduced by two users including me) without adding the following flags
```
$ mvn install -Dmaven.javadoc.skip=true -DskipTests=true
```
Also, junit is causing problems that can be fixed by this
https://stackoverflow.com/questions/55272870/surefire-maven-plugin-corrupted-stdout-by-directly-writing-to-native-stream-in
but this is not the only issue.

**Comment by ielis** [comment]
This should work now
