### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenol#326]
Having RTD docs would be awesome!

javadocs is a good placeholder - however, the README links to what I think is very old ontolib docs? E.g.

https://javadoc.io/doc/com.github.phenomics/ontolib-core/0.3/com/github/phenomics/ontolib/formats/mpo/MpoTerm.html

this is no longer in phenol, correct?

**Comment by pnrobinson** [comment]
I agree -- the API is starting to settle down enough that we should start trying to attract outside users more.

**Comment by pnrobinson** [comment]
The readthedocs is here

https://phenol.readthedocs.io/en/latest/

I will add it to the main README
