### ISSUE TITLE
snakeyaml

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#333]
Do we really need to have this external dependency? Why are we parsing YAML anyway?

**Comment by julesjacobsen** [comment]
Because JSON <-> YAML and it is possible to produce the ontologies in YAML, so...

But yes, it is incredibly irritating that snakeyaml doesn't support the module system.

**Comment by ielis** [comment]
Well, at least they do provide `Automatic-Module-Name` in the manifest as of `v1.27`.

**Comment by ielis** [comment]
This should not be an issue anymore in the recent phenol versions.
