### ISSUE TITLE
Modernize ontologizer code

### ISSUE THREAD

**Issue by ielis** [monarch-initiative/phenol#340]
Review the Ontologizer code and put it into separate phenol module.

**Comment by pnrobinson** [comment]
Note the Ontologizer code is an a separate module (phenol-analysis). It makes use of the Term, TermId, Ontology, and OntologyAlgorithm classes in phenol-core. I have done a lot of work to update the code, some of which was initially Java 1.5, but there is still work to be done. I am going to start by adding a few Interfaces for some of the key items and adding some additional unit tests. I also think that some of the code could be simplified/elegant-ified

**Comment by pnrobinson** [comment]
Some interfaces added now (development branch) and some cleanup has been performed.

**Comment by pnrobinson** [comment]
@ielis I think this is now finished, although at some point we should revisit the ontologizer code and decide if it really wants to live here.
