### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/io/input/BOMInputStream

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#362]
By accident I tried to load an hp.obo file and got this exception. I am not sure if it is actually related to phenol, but we should probably throw an exception if we see that somebody is trying to parse a *.json or *.owl file

**Comment by julesjacobsen** [comment]
Did you have anything else in the stacktrace?

**Comment by pnrobinson** [comment]
already fixed everything :-0. But still it would be good to provide this exception rather than something generic from deep in the stack call

**Comment by ielis** [comment]
I saw `NoClassDefFoundError` the other day when there were >1 versions of the same artifact on the classpath. This should not be happening with phenol anymore.
