### ISSUE TITLE
HpoDiseaseAnnotationMetadata should contain source

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#374]
We need this to display on the Webpage, e.g.,  [OMIM:154700](https://hpo.jax.org/app/browse/disease/OMIM:154700)  has a mix of citations to OMIM and PubMed. Note that there can be multiple annotations to different sources so we need to return a list

**Comment by pnrobinson** [comment]
Something like this?
```
List<TermId> modifiers = annot.metadata()
                .map(HpoDiseaseAnnotationMetadata::modifiers)
                .flatMap(Collection::stream)
                .toList();
```

**Comment by ielis** [comment]
As pointed out by this issue, each `HpoDiseaseAnnotationMetadata` should have a source, consisting of `TermId` and `EvidenceCode` (`PCS`, `IEA`, etc.).  Moving forward, the `HpoDiseaseAnnotation` provides aggregations to get frequencies, onsets, modifiers, etc. However, we need to support this with the existing data.

The HPOA file contains a record like:
```
OMIM:215140     Greenberg dysplasia             HP:0008905      OMIM:215140;PMID:14684697       PCS             11/11                   P       HPO:probinson[2021-11-24];HPO:skoehler[2012-10-17]
```
The issue with the record is that it lists an exact ratio `11/11` but two references. It is not clear which reference is the source of the ratio. Was it `5/5` + `6/6`, or `11/11` + `0/0`? In ideal world, we would have this information to make it easier to fix possible curation errors.

There is one record supported by `7` references:
```
OMIM:215140     Greenberg dysplasia             HP:0000773      PMID:11113916;PMID:11180245;PMID:3377005;PMID:8213919;PMID:14684697;PMID:12618959;PMID:12210303 PCS                                     P       HPO:iea[2012-07-25]
```

Then:
```
#records  #references
1         233492
2           2022
3            242
4             26
5              5
6              3
7              1
```
(2299 records with `>1` reference).

Should this be a big deal?

**Comment by pnrobinson** [comment]
The original small files (and the corresponding records in the database) will have one reference per line. The phenotype.hpoa aggregates the references. For most downstream use people do not need the PMIDs, and so to save space we could just leave them in a separate file, but I do not think we are limited by this kind of space right now?
For curation, we will have the original data and will not be starting from this aggregated file.

**Comment by ielis** [comment]
I do not think we are limited by space in HPOA files either. If the file grows, we should be compressing it. The compression saves tons of space since there is a lot of duplicated text in the file:

- `phenotype.hpoa` 27M
- `phenotype.hpoa.gz` 1.9M

Would it be a big issue to change the pipeline and do not aggregate the references?
