### ISSUE TITLE
"negative terms"

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#379]
We decided to remove the "negative terms" but it would be useful to have a function in HpoDiseaseAnnotation that would return a boolean for whether a term is recorded as having a zero frequency (or even better, hasa a frequency below an argument to the function).
If the term has no Frequency annotation, return false (because we assume frequency = 1.0). Otherwise check the frequency within the function. Otherwise we are exposing a lot of logic of the Frequency class

**Comment by ielis** [comment]
How about adding `boolean isAbsent()`?

```java
public interface HpoDiseaseAnnotation {

  // ... skipped

  /**
   * @return ratio representing number of individuals with this {@link HpoDiseaseAnnotation} or an empty optional
   * if no occurrence data is available.
   */
  Optional<Ratio> ratio();

  /**
   * @return {@code true} if the annotation was not observed in the disease.  
   */
  default boolean isAbsent() {
    return ratio().map(Ratio::isZero)
      .orElse(false);
  }
}
```

I think we should be OK with `Ratio::isZero` as we're not doing equality checks to double, the numerator in `Ratio` is `int`.

**Comment by pnrobinson** [comment]
Well, the way we are using this data is that if the annotation for frequency is absent, we assume some default frequency, but definitely not zero. I think that a better default would be a ratio of 1/1, because the existence of the annotation means that a clinician reported the feature in some context!

**Comment by pnrobinson** [comment]
I see, I was misunderstanding, I thought this meant that there was no frequency information at all. Yes, then isAbsent is probably a reasonable function name
