### ISSUE TITLE
Design pattern issue for new ontology parser

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#39]
@yy20716 
Hi HyeongSik
I guess that this is the class that we will use to parse OBO ontologies?
Are we going to run into problems down the line because most ontologies have mutliple TermRelation types?
```
OwlImmutableOntologyLoader<T extends Term, R extends TermRelation>
```
Or will we get around this if we use the ``GenericTermRelation`` with a ``GenericRelationQualifier`` that is a superclass of all others in the ontology? Are we ready to start testing this on MONDO or HPO?

**Comment by cmungall** [comment]
I think this is a good time to change some of the underlying terminology in phenol which is confusing and different from all other ontology libraries.

What ontolib called a 'TermRelation', we call either 'Relationship' or 'Edge' (or Axiom or Triple or Fact or Statement...).

What ontolib called RelationQualifier, we call either 'Relation' or 'RelationshipType' or 'Property' (or ObjectProperty or EdgeLabel or....)

I'd like to do a proper cleanup here and do this right, see my comments in #9

**Comment by yy20716** [comment]
* I just checked this post. When I analyzed the original ontolib codes, it seemed that the assumption behind the codes was that each ontology is supposed to be mapped over its own `TermRelation` and `TermQualifier` classes; so, as a quick workaround, I built generic-* classes for generic owl files (these classes are basically the same as the ones for GO, though).
    - I guess your workaround (i.e. making `GenericTermRelation`/`RelationQualifier` as superclasses) would be the one way to solve this issue. I will try to re-arrange classes as Peter suggested. 
   - Please note that `OwlImmutableOntologyLoader` is the wrapper class for loading generic **owl** files using Obographs, so it's not the one for generic **obo** files. 

* I am still in the middle of replacing the internal graph library with JGraphT. Once this part is done within a few days, I will begin revising the name of obo-specific classes such as `TermRelation`/`RelationQualifier`, as Chris suggested. Thank you.

**Comment by yy20716** [comment]
I just wanted to note that the merged codes already use the `GenericTermRelation` with a `GenericRelationQualifier` that is a superclass of all others in the ontology, as suggested. In addition, the class names are renamed based on the suggestions from Chris. It would be okay if we could close this issue and make another one for discussing about MONDO/HPO parsers.

**Comment by pnrobinson** [comment]
I agree, let's close this issue and make specific issues for the various other items.
