### ISSUE TITLE
Obsolete Terms

### ISSUE THREAD

**Issue by iimpulse** [monarch-initiative/phenol#423]
https://github.com/monarch-initiative/phenol/blob/0da2c42a5c493173a03c90108560da378d89b182/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/data/MinimalOntology.java#L111

The comment instructs this returns obsolete terms. Is this true?

**Comment by ielis** [comment]
The documentation has been fixed to indicate that the method does *not* provide obsolete terms to resolve the ambiguity.
