### ISSUE TITLE
ontology version

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#430]
It would be nice to add a convenience function to retrieve the ontology version. Now we need to do this
```
Ontology ontology = OntologyLoader("...");//
String version = ontology.getMetaInfo().getOrDefault("data-version", "unknown version");
````
but this is a relatively common operation and it is hard to remember the exact steps without searching for it.
It would be nice to have a function in the Ontology class that would be like this

```
String getVersion() {
   return getMetaInfo().getOrDefault("data-version", "unknown version");
}
```
or possibly

```
Optional<String> getVersion() {
   return Optional.ofNullable(getMetaInfo().getOrDefault("data-version"));
}
```

**Comment by ielis** [comment]
Now [`MinimalOntology`](https://github.com/monarch-initiative/phenol/blob/master/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/data/MinimalOntology.java) extends [`Versioned`](https://github.com/monarch-initiative/phenol/blob/master/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/data/Versioned.java), so version is available as an optional attribute.
