### ISSUE TITLE
leakage

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#452]
phenol seems to be "leaking" the google MultiMap (guava) implementation in a downstream modular application. 
It would be good to remove dependencies on guava, which are less necessary now than 10 Java versions ago. ?

**Comment by ielis** [comment]
I believe this is because of Obographs. Phenol needs Obographs and Obographs in turn needs Guava. There is nothing we can do in Phenol.

**Comment by pnrobinson** [comment]
I am getting an exception, Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) that is coming from the OntologyTree module 

I do not have "requires com.google.guava" in my module def file

**Comment by ielis** [comment]
This may be due to a pom file. Can you pls point me to the repo?

**Comment by pnrobinson** [comment]
https://github.com/monarch-initiative/hpo2robot

**Comment by ielis** [comment]
It looks you are excluding `guava` [here](https://github.com/monarch-initiative/hpo2robot/blob/616b61d1d7a8b839a2bae24fe9cda3a74f2cbf94/pom.xml#L95). Can you try to remove the exclusion?

**Comment by pnrobinson** [comment]
That does not affect the error ...

**Comment by ielis** [comment]
I guess we should hack on this in person in lunch? Where should we meet after the session?

**Comment by julesjacobsen** [comment]
I'm going to be doing a bit of work on OboGraphs this week - let me see if I can remove that dependency.

**Comment by julesjacobsen** [comment]
[obographs-core-0.3.1](https://github.com/geneontology/obographs/releases/tag/v0.3.1) is now guava-free. If you're depending on the obographs-owlapi then guava is still pulled in as a transitive dependency of the OWLAPI.

**Comment by pnrobinson** [comment]
Fantastic! Thanks! I will leave this open until we update the dependency

**Comment by ielis** [comment]
We should be guava-free as of `v2.0.4` (latest release):

```shell
 ./mvnw dependency:tree | grep "guava" | wc -l
0
```
