### ISSUE TITLE
HpoTermId

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#55]
I have implemented a TermId class that has additional metadata about an annotation. I am worried that my implementation is suboptimal because (Immutable)HpoTermId also implements TermId, which led in one case to a bug because client code passed an ImmutableHpoTermId object to a function that was expecting an ImmutableTermId object leading to non-equality issues. (i.e., a Map that was initiailized with TermId for HP:1234567 did not think that an ImmutableHpoTermId initiallzed to HP:1234567 
 with other metadata was "equal".
@julesjacobsen @yy20716 I would appreciate your insight on this. AFAIK this is a recognized issue (e.g., the Bloch book) and there are several possible workarounds.

**Comment by julesjacobsen** [comment]
Can you copy in the relevant bits of code here, or link to them?

**Comment by pnrobinson** [comment]
See here for the HpoTermId and ImmutableHpoTermId classes
https://github.com/monarch-initiative/phenol/tree/master/phenol-core/src/main/java/org/monarchinitiative/phenol/formats/hpo

The issue that I encountered was basically this. I did calculations to fill this map:
```
private ImmutableMap<TermId, Double> specialMap = null;
```
I was putting ImmutableTermId objects into the map.
Later on in the code, I was using an ImmutableHpoTermId object and passing it to a function that looked like this
```
public void doCoolStuff(TermId tid) {
    if (this.specialMap.containsKey(tid)) {
        // do something really impressive
   } else {
     // be really disappointed
   }
} 
```

and calling the function like this
```
HpoTermId htid = // create HpoTermId
doCoolStuff(htid);
```

**Comment by julesjacobsen** [comment]
Did this map really have to contain ```TermId``` and not use the actual ```HpoTermId```?  Also it depends on how you define ```equals()```. As you say Josh Bloch has advise on this.

**Comment by pnrobinson** [comment]
Just make this not extend TermId

**Comment by pnrobinson** [comment]
This issue dealt with by https://github.com/monarch-initiative/phenol/pull/58

**Comment by julesjacobsen** [comment]
Aaah, I see what you were trying to do now. Yes, use a compound Annotation class with the TermId as a member.
