### ISSUE TITLE
DbXref

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#62]
There are two classes with this name in phenol -- org.monarchinitiative.phenol.io.obo.DbXref
org.monarchinitiative.phenol.ontology.data.Dbxref (an interface).
(There is one capitalization difference)
-- this is mixing up my IDE and it is unclear to me that this is necessary. Figure out what to do here.

**Comment by yy20716** [comment]
From my observation, it seems that these two classes, [DbXref](https://github.com/monarch-initiative/phenol/blob/master/phenol-io/src/main/java/org/monarchinitiative/phenol/io/obo/DbXref.java) and [ImmutableDbxref](https://github.com/monarch-initiative/phenol/blob/master/phenol-core/src/main/java/org/monarchinitiative/phenol/ontology/data/ImmutableDbxref.java), are almost identical except the part that handles TrailingModifier (the ImmutableDbxref is the one that implements Dbxref interface). In fact, DbXref instance is later transformed into ImmutableDbxref as the process of construcing term object (e.g., [GoOboFactory](https://github.com/monarch-initiative/phenol/blob/630ced8bf36fe113f86ebef0f3a7b83b68ef4e4e/phenol-io/src/main/java/org/monarchinitiative/phenol/io/obo/go/GoOboFactory.java#L173)). I guess we could remove one of them. Let me check and refactor these codes.

**Comment by pnrobinson** [comment]
I think this is working now.
