### ISSUE TITLE
Mondo Parser, get Name oddity

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#65]
In the following code in HPO Workbench
```
MondoParser parser = new MondoParser(pathToMondoFile);
ImmutableOntology<GenericTerm,GenericRelationship> mondo = parser.parse();
int n = mondo.getTermMap().size();
logger.trace("Parsed Mondo ontology and found "+ n+ " terms");
Map<TermId,GenericTerm> termmap = mondo.getTermMap();
for (TermId tid : termmap.keySet()) {
    GenericTerm gt = termmap.get(tid);
     logger.trace(getDefinition());
...
}
```
is picking up some non- MONDO terms:
It also never finds xrefs (not shown below, but tested with 100 MONDO classes)

TRACE [main] (MondoCommand.java:47) - realized in: BFO:0000054
TRACE [main] (MondoCommand.java:51) - No xrefs
TRACE [main] (MondoCommand.java:47) - definition: IAO:0000115
TRACE [main] (MondoCommand.java:51) - No xrefs
TRACE [main] (MondoCommand.java:47) - term replaced by: IAO:0100001
TRACE [main] (MondoCommand.java:51) - No xrefs

**Comment by pnrobinson** [comment]
@yy20716 For the HPO Workbnench and the merging of annotations from Orphanet and OMim diseases that both map to some Mondo Id, I will need to have access to the xrefs (I think) -- or maybe there is another way? Basically, what I would like to do is this
```
GenericTerm gt = // get your favorite Mondo disease
DbXrefs xrefs  = gt.getXrefs();
// search xrefs to find Strings such as OMIM:612354 or ORPHA:42654 (even better, Termids, but let's leave that for later!)

**Comment by pnrobinson** [comment]
The main issue is that the parser is not picking up any xrefs. But in application code, we should decide whether we want to use the owl or the simplified obo version. Let's discuss next week.

**Comment by yy20716** [comment]
Hello, I guess we could discuss what would be the best way to solve this issue. I checked the codes and they only currently read xrefs of synonyms right now. I remember that I was not sure what to do with other xrefs in ontologies when I built these codes; I guess at least for now I can adds codes for reading all existing xrefs. Thank you.

**Comment by yy20716** [comment]
For now, I extended the loader codes to read xref entries (see also [this pull request](https://github.com/monarch-initiative/phenol/pull/68)). If you also need to process equivalence classes for your HPOworkbench, please let us know. Thank you.

**Comment by pnrobinson** [comment]
I think this problem has been solved some time ago, closing.
