### ISSUE TITLE
Make the datamodel ontology-generic

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenol#7]
Currently we have

 - com.github.phenomics.ontolib.io.obo.mpo.MpoOboParser
 - com.github.phenomics.ontolib.io.obo.mpo.MpoOboFactory
 - com.github.phenomics.ontolib.formats.mpo.MpoOntology
 - com.github.phenomics.ontolib.formats.mpo.MpoTerm
 - com.github.phenomics.ontolib.formats.mpo.MpoTermRelation

For HPO, MPO, GO, Vegetable, …?

Either

 - Remove the {Hpo,Mpo,..}{Term,Ontology,Relation} classes (preferred)
 - Make  AnyOntology{Term,Ontology,Relation} classes (compromise)

Note: it’s OK to have specific classes for annotations (e.g. GAF vs HPOA)

**Comment by pnrobinson** [comment]
I would suggest we see if we can implement an HPO OBO parse using a generic term and relation class and if it works then replace this part of ontolib. 
There are other possible ingest use cases, e.g., ZFIN or using hp-edit.owl to get more term attributes (not the full owl model) that we should also consider.

**Comment by cmungall** [comment]
On Feb 6, 2018 18:28, "Peter Robinson" <notifications@github.com> wrote:

I would suggest we see if we can implement an HPO OBO parse using a generic
term and relation class and if it works then replace this part of ontolib.

Sounds good

There are other possible ingest use cases, e.g., ZFIN or using hp-edit.owl
to get more term attributes (not the full owl model) that we should also
consider.

Not sure what you mean by zfin? ZP? Either way the one parser should be
able to handle all ontologies

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/monarch-initiative/OLPG/issues/7#issuecomment-363635512>,
or mute the thread

**Comment by julesjacobsen** [comment]
Common classes all the way please. If we need a specific implementation a composite value class will probably be the easiest and most flexible route.

i.e. Term, Ontology, Relation interfaces. These could contain static factories returning a concrete instance of a base type. 

e.g.
```java
public interface Term {
  
  public String getId();
  public String getLabel();

  public static Term of(id, label) {
     return new BaseTerm(id, label); 
  }
}
//note this is not public 
final class BaseTerm implement Term {
}

public class HpoTerm implements Term {
//this could delegate its term implementation to the result of Term.of(), 
//it  might be a bit bloated memory-wise especially as term is so simple.
// But it could save nasty inheritance issues.  
}
```
but if you need something specific from an HPO class then create an HpoTerm which wraps the Term and also provides extra functionality.

**Comment by pnrobinson** [comment]
I think this issue has now been implemented by HyeongSik, I will close it.
