### ISSUE TITLE
?graph algorithm for finding common ancestor

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#76]
We have the use case of having one query term and we would like to find out if it has a common ancestor with any of the terms that annotate some disease (we would like to have a list or set of all such common ancestors).
Current we are doing this one-by-one in a for loop for each of the terms to which a disease is annotated.
It might be more efficient to calculate the subgraph that is induced by the annotated terms consisting of the terms and all of their ancestors, and then to perform a second operation that would find all of the common ancestors (we would do this for all query terms, so we would want to store the induced graph and be able to operate on it multiple times).
For some downstream algorithms we would want to know the path distance between the query term and the identified common ancestor, so it would also be good to have a function that would calculate path length.
So one simple implementation would be something like this
```
Set<TermId> explicitlyAnnotatedTerms =  disease.getPhenotypeAnnotations());
Map<TermId,Integer> mp = new HashMap<>(); // value will be distance from root
breadth first search:
-- keep track of current distance from root
-- if we visit a term in explicitlyAnnotatedTerms, add it to mp with the distance
-- stop the BFS if we have visited all of the explicitlyAnnotatedTerms
```
We already have a function called ``existsPath`` which could be adapted to return the shortest path length.
if we also looked for all of the query terms during the BFS, we can record their distance to the root and estimate the distance to the common ancestor by subtracting). Not always correct but maybe good enough for government use?

@yy20716 @cmungall  does this make sense? Are there better ways of doing this?

**Comment by cmungall** [comment]
you might want to look at porting some of the owlsim3 code over, it has efficient operations for common ancestors using bitsets. (the owlsim2 code currently driving the monarch site uses similar code but messier).

cc @julesjacobsen @kshefchek

**Comment by cmungall** [comment]
Best looked at in an IDE

This is the underlying low-level class

https://github.com/monarch-initiative/owlsim-v3/blob/a4a9c23208b2924caf48d363a02700258f9b49c1/owlsim-core/src/main/java/org/monarchinitiative/owlsim/kb/ewah/EWAHKnowledgeBaseStore.java

Example code to get the MRCA plus it's frequency:

https://github.com/monarch-initiative/owlsim-v3/blob/5bba20a985bb5265dde9681642f284913f0ccaaf/owlsim-core/src/main/java/org/monarchinitiative/owlsim/compute/mica/impl/MostInformativeCommonAncestorCalculatorImpl.java#L52-L64

**Comment by pnrobinson** [comment]
This looks pretty nice. It might also be a good idea to port some of the classes used here such as ClassFrequencyPair, since I think a lot of algorithms will need to have not only matches but also some information about the matched class. Should we touch bases about how to proceed here?

**Comment by pnrobinson** [comment]
This kind of code is used in the Resnik class, I think we can close this issue from now.
