### ISSUE TITLE
NCIT parser

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#77]
I would like to try and implement an NCIT parser that will wrap the bare OBO or OWL parse and that can be instantiate with a series of constants that will instruct the parse which portions of NCIT to extract. I would like to have code that will output triples from this in a way that we can use for the projE project.
@yy20716 @cmungall do you have advice or code that we could use for this? Otherwise, I will prototype a parse on a separate branch and would love to get feedback.

**Comment by cmungall** [comment]
Why not just do a SPARQL query? cc @balhoff

**Comment by balhoff** [comment]
Could you describe more what sort of triples you want to output? Is this like `NCIT:nnnn subClassOf NCIT:xxxx`? If so we can likely do that with a SPARQL CONSTRUCT on the graph store.

**Comment by pnrobinson** [comment]
That might work actually. I would like to have the complete graphs of all of the classes and ancestors that are used to define the cancer diagnoses. I guess the problem is that Jim said it would take 80GB RAM to construct a SPARQL database that would do that?

**Comment by cmungall** [comment]
It shouldn't take that much, I have queried larger triplestores on my laptop.

In any case you can just use https://stars-app.renci.org/ncitgraph/sparql

**Comment by cmungall** [comment]
I'm guessing the query will be something like all neoplasms, their superclasses (both named and existentials - e.g. links to uberon, genes, drugs, ...)

**Comment by pnrobinson** [comment]
@balhoff didnt you say that it required lots of resources to create the closure you are using for the online triple store? Or did I misunderstand. Currently, I do not think that either option would get me 100% over the goalline. But clearly everybody thinks we should not be parsing the OBO file for this. I mean basically that each NCIT cancer class has maybe 10 axioms about the characteristics of the cancer. I want to get all of these plus all relevant parts of the subhierarchy. I cannot use Jena to do this because it will not parse the entire file. I guess I could use OWL API. But I thought the whole point of the obo file was to make this easier?

**Comment by balhoff** [comment]
@pnrobinson that was to build the triplestore including all the pre-reasoning stuff. But it sounds like you need that reasoning, because in many cases those characteristics are embedded in equivalent class axioms. The triplestore has a graph that flattens all this into direct property triples.

**Comment by pnrobinson** [comment]
This issue has gotten stale. The basic parser is working, although it needs more features. Closing...
