### ISSUE TITLE
Align with OBOGraphs as an underlying datamodel

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenol#8]
https://github.com/geneontology/obographs/

The core model here is a simple property graph, same as what underpins most graph libraries. The model is essentially:

```
GraphSet := Graph*
Graph := Meta Node* Edge*
Node := ID Label Meta?
Edge := Subj Rel Obj Meta?
```

The meta objects are optional and provide rich intuitive representation of things like synonyms. There is also extensions for more complex OWL axioms but these are optional. It’s designed for easy bioinformatics-style graph processing, with the option of doing more advanced stuff with either OWL axioms or things like synonyms.

https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

**Comment by pnrobinson** [comment]
This is now implemented
