### ISSUE TITLE
Removing template for Ontology

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#82]
@cmungall 
I would remove the template since we want to have one Term and one Relation. Do you see any reason to keep these? It does not even make sense to me because an ontology can have multiple relationship types and so it is hard to capture that with a single template. 
current
Ontology<T extends TermI, R extends RelationshipI>
proposed
Ontology
(and always [generic] term and relation)

**Comment by cmungall** [comment]
I see no reason to keep these

**Comment by pnrobinson** [comment]
I have simplified the code by moving towards one single Term and one Relation class and removing some templates and interfaces. This is not in branch mpoParser. After this has been tested with MPO I will merge to the main branch.
