### ISSUE TITLE
TermId vs ImmutableTermId

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#87]
I do not see the need for having an Interface to TermId -- we have no ontologies that do not use the pattern XY:123 for the term ids and it adds an extra layer of complexity that does not bring any advantages. 
@cmungall Do you see any case for retaining this?

**Comment by cmungall** [comment]
Yes, all URIs can be reduced to CURIEs, given a context jsonld file.

**Comment by pnrobinson** [comment]
this doesn't seem to be "Yes, this is a case for retaining the interface", but instead "Curies make the interface superfluous"? :-0

**Comment by pnrobinson** [comment]
OK, I have implemented this.
