### ISSUE TITLE
Remove OBO Format peculiarities

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/phenol#9]
Ontolib’s datamodel is strongly based on obo-format, which IMHO is not a good decision

I'm wondering about:

https://github.com/Phenomics/ontolib/blob/8bcd1fa07dbd0c911d886dad5844119958d27e66/ontolib-core/src/main/java/com/github/phenomics/ontolib/formats/go/GoRelationQualifier.java#L13

This seems unusual, I don’t know what the use case for this.

It is far more standard to treat IS_A as a relationship type (along with part_of, develops_from, regulates, etc). Stuff like the OBO intersection_of tag should be handled in an optional OWL extension. Using an obo-format level of abstraction for non-graphy OWL stuff is a bad idea (I say this as the person primarily responsible for foisting obo format on the world)

**Comment by pnrobinson** [comment]
afaik the GO support of ontolib is still preliminary, and I doubt that any code has been written with this part of the ontolib library. I think that the only reasonable way forward is just to correct all infelicities, errors, and omissions, and then either we will merge with ontolib in the future or not.

**Comment by pnrobinson** [comment]
I think that this issue has become obsolete with our switch to the OWL API parser.
