### ISSUE TITLE
ClassBasedEdgeFactory from JGraphT is deprecated

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#91]
Consider whether we can refactor, see
http://jgrapht.org/javadoc/org/jgrapht/graph/ClassBasedEdgeFactory.html

**Comment by pnrobinson** [comment]
This is the supplier interface (EdgeProvider is deprecated and the Supplier interface is recommended).
https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html?is-external=true
I am not sure about which implementation to use or whether the default implementation is correct.

**Comment by julesjacobsen** [comment]
Unless I've totally misunderstood this all, there is no real point to the existence of the ClassBasedEdgeFactory.

This Phenol code from [OboImmutableOntologyLoader](https://github.com/monarch-initiative/phenol/blob/89166934d6ef5abbf7b92f15a9f9aed9e710b118/phenol-io/src/main/java/org/monarchinitiative/phenol/io/obo/OboImmutableOntologyLoader.java#L109-L126)

```java
  final ClassBasedEdgeFactory<TermId, IdLabeledEdge> edgeFactory = new ClassBasedEdgeFactory<>(IdLabeledEdge.class);
...
  IdLabeledEdge edge = edgeFactory.createEdge(sourceTermId, targetTermId);
  edge.setId(b.getRelation().getId());
  graph.addEdge(sourceTermId, targetTermId, edge);
```
can be replaced by a simple:

```
  IdLabeledEdge edge = new IdLabeledEdge();
  edge.setId(b.getRelation().getId());
  graph.addEdge(sourceTermId, targetTermId, edge);
```

The `ClassBasedEdgeFactory` implementation is this (_n.b._`source` and `target` are unused):
 
``` java
    @Override
    public E createEdge(V source, V target)
    {
        try {
            return edgeClass.getDeclaredConstructor().newInstance();
        } catch (Exception ex) {
            throw new RuntimeException("Edge factory failed", ex);
        }
    }
```
which here just looks like a super-overblown way of simply calling 'new'. As for the `Supplier` interface, you could implement it like this, but I'm still unclear why you'd want to.

```java
class EdgeFactory {

    public <E extends DefaultEdge> Supplier<E> getInstance(Class<E> edgeClass) {
      return () -> {
        try {
          return edgeClass.getDeclaredConstructor().newInstance();
        } catch (Exception ex) {
          throw new RuntimeException("Edge factory failed", ex);
        }
      };
    }
}
// then using the class:
Supplier<IdLabeledEdge> edgeFactory = new EdgeFactory().getInstance(IdLabeledEdge.class);
...
IdLabeledEdge edge = edgeFactory.get();
edge.setId(b.getRelation().getId());
graph.addEdge(sourceTermId, targetTermId, edge);
relationMap.put(b.getRelation().getId(), b.getRelation());
```

**Comment by pnrobinson** [comment]
Thanks for looking into this -- I have simplified the code as suggested above and was thereby able to remove the reference to the deprecated class
https://github.com/monarch-initiative/phenol/commit/1553bfbb25193c43f76a8342a4c7cfc9f549bac2

**Comment by julesjacobsen** [comment]
I think that there are other classes using the `ClassBasedEdgeFactory` apart from the `OboImmutableOntologyLoader`
