### ISSUE TITLE
Add support for disease<->gene ingest

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#95]
* Use medgen file ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/mim2gene_medgen

Question for Dipper team -- it seems there is an obvious way to ingest this data
for instance the line:
154700  2200    phenotype      
means OMIM:154700 (Marfan syndrome) is related to Entrez Gene 220 (FBN1) and so on....
-- Are we doing anything special/different in dipper that we need to be aware of for the phenol code?

@TomConlin
@cmungall 
@kshefchek
@hannahblau

**Comment by TomConlin** [comment]
just that the g2p association is reified so evidence/provenance other supporting details may be attached to each association. Checking with Matt for preferred ontology terms is probably a good idea.

**Comment by pnrobinson** [comment]
Ok! This is all going into a Java object and being used for calculations so we do not need to store provenance here. I am guessing that phenol is now capturing more metadata about the annotations that dipper, and so we should coordinate on that at some point!

**Comment by pnrobinson** [comment]
I have start to implement this in a new branch
https://github.com/monarch-initiative/phenol/tree/gene2phenParser
I will use the mim2gene_medgen and the Homo sapiens gene_info.gz files. 
For downstream usages, we could either add gene<->disease annotatations to HpoDisease objects or store everything in some kind of Map. I am currently tending to the second option, but want to explore a bit more before settling on one or another approach.

**Comment by kshefchek** [comment]
You might consider https://data.monarchinitiative.org/tsv/gene_associations/gene_disease.9606.tsv, but it's HGNC to MONDO.  If you are wed to entrez and OMIM we could generate a different file. The is_defined_by column can be used to filter out data from OMIM.

**Comment by pnrobinson** [comment]
It would be good to talk about this. The HGNC is not easy for use downstream, I wish that we could have Entrez gene ids instead or in addition. Also, it would be good to have some idea of what kind of association there is between the gene and the disease. For now, we will need to stick with OMIM ids, until more dust has settled. But let's plan on working on this file so that we can use it in our downstream apps in the future.
thanks!

**Comment by pnrobinson** [comment]
This is now working -- @pnrobinson check in new test files.

**Comment by pnrobinson** [comment]
Working now, all is checked in.
